# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # The command to build the docs does the following:
  #
  # - Modify the LOAD_PATH so that we could load the code in src/PlotDocs.jl
  # - Instantiate the dependencies in the Project.toml
  # - Run docs/make.jl to build the docs
  # - Use a YAML block scalar (|) for a proper multiline command
  #
  - |
    JULIA_LOAD_PATH="$PWD/src/:@:@stdlib" julia --project --color=yes -e'
        using Pkg
        Pkg.instantiate()
        include("docs/make.jl")
    '
