# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'import Pkg; Pkg.add(Pkg.PackageSpec(path = pwd())); Pkg.add("Documenter"); cd(joinpath(dirname(pathof(PlotDocs)), "..", "docs")); include("make.jl")'
