language: julia
os:
  - linux
julia:
  - 1.1
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      env:
        - PYTHON=""
      addons:
        apt:
          packages:
            # pgfplots
            - pdf2svg
            - texlive-latex-base
            - texlive-binaries
            - texlive-pictures
            - texlive-latex-extra
            # orca
            - libgconf2-4
      script:
        - xvfb-run julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - xvfb-run julia --project=docs/ docs/make.jl
      after_success: skip
