site_name: Plots
repo_url: https://github.com/tbreloff/Plots.jl/
site_author: Thomas Breloff
copyright: 2015-2016 Thomas Breloff
pages:
- 'Home': 'index.md'
- 'Installation': 'install.md'
- 'Basics': 'basics.md'
- 'Backends': 'backends.md'
- 'Attributes': 'attributes.md'
- 'Input Data': 'input_data.md'
- 'Internals': 'pipeline.md'
- 'Layouts': 'layouts.md'
- 'Recipes': 'recipes.md'
- 'Plots v0.7: plots_v'0.'7.md'
- 'Supported Attributes': 'supported.md'
- 'Examples': 'examples.md'
# theme: readthedocs
theme: slate