site_name: "Plots"
repo_url: "https://github.com/tbreloff/Plots.jl/"
site_author: "Thomas Breloff"
copyright: "Copyright &copy; 2015-2016 Thomas Breloff"
pages:
- "Home": "index.md"
- "Installation": "install.md"
- "Backends": "backends.md"
- "Basics": "basics.md"
- "Input Data": "input_data.md"
- "Attributes": "attributes.md"
- "Colors": "colors.md"
- "Output/Display": "output.md"
- "Internals": "pipeline.md"
- "Layouts": "layouts.md"
- "Recipes": "recipes.md"
- "Plots v0.7": "plots_v0.7.md"
- "Supported Attributes": "supported.md"
- "Examples":
  - "PyPlot": "examples/pyplot.md"
  - "GR": "examples/gr.md"
  - "PlotlyJS": "examples/plotlyjs.md"
  - "UnicodePlots": "examples/unicodeplots.md"
theme: readthedocs