
# NOTE: to build, run `mkdocs build --clean` from the `PlotDocs.jl` directory
#       then push the changes to the githubio remote (juliaplots.github.io)

site_name: 'Plots'
site_author: 'Thomas Breloff'

repo_name: 'GitHub'
repo_url: 'https://github.com/tbreloff/Plots.jl'

copyright: 'Copyright &copy; 2015-2016 Thomas Breloff'

pages:
  - Home: index.md
  - Installation: install.md
  - Backends: backends.md
  - Basics: basics.md
  - Input Data: input_data.md
  - Attributes: attributes.md
  - Colors: colors.md
  - Output: output.md
  - Animations: animations.md
  - Internals: pipeline.md
  - Layouts: layouts.md
  - Recipes: recipes.md
  - Plots v0.7: plots_v0.7.md
  - Supported Attributes: supported.md
  - Examples:
    - PyPlot: examples/pyplot.md
    - GR: examples/gr.md
    - PlotlyJS: examples/plotlyjs.md
    - PGFPlots: examples/pgfplots.md
    - UnicodePlots: examples/unicodeplots.md

docs_dir: 'docs'

# theme: readthedocs
theme: material

extra:
  author:
    github: 'tbreloff'
  palette:
    primary: 'deep orange'
    accent: 'indigo'
  version: 0.7.4

markdown_extensions:
    - admonition
    - codehilite(css_class=code)
    # - mdx_math:
    #     enable_dollar_delimiter: True

extra_javascript: [
     'mathjax-config.js',
     'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
]
